---
name: insta_clone
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  google_fonts: ^2.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  sqflite: ^2.0.0+4

flutter:
  assets:
    - assets/facebook.png
    - assets/instagram_logo.jpg
    - assets/ins.png
    - assets/insta.png
    - assets/facebook1.png
    - assets/google.png


environment:
  sdk: '>=3.0.6 <4.0.0'


uses-material-design: true


publish_to: none

version: 1.0.0+1
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

  # see https://flutter.dev/custom-fonts/#from-packages